### ISSUE TITLE
jupyter notebook + singularity witout sudo

### ISSUE THREAD

**Issue by kkmann** [sylabs/examples#62]
hey @devprincess, I'd be interested in packaging jupyter notebook + IRkernel and same other R packages I need for an analysis in a singularity container. I gave the example https://github.com/sylabs/examples/tree/master/machinelearning/jupyter-notebook a shot but it seems to require sudo to run the jupyter server. 
I'd really just like to

    singularity run jupyter.sif

and get a notebook server opened in the current working directory on localhost. Using this setup, however, 

    Bootstrap: docker
    From: rocker/verse
    %post
        apt-get update
        apt-get -y install curl wget python3-pip

        # install snakemake
        pip3 install snakemake

        # install jupyter notebook
        python3 -m pip install jupyter
        python3 -m pip install nbconvert

        # install R kernel
        R -e "install.packages('IRkernel'); IRkernel::installspec()"

    %runscript
        jupyter notebook --allow-root "$@"

I run this using

```
singularity exec --bind $PWD:/run/user image.sif jupyter notebook --ip=127.0.0.1 --no-browser
```

I can only run python kernels, switching to the R kerneln results in an error

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python2.7/site-packages/notebook/services/sessions/handlers.py", line 73, in post
    type=mtype))
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python2.7/site-packages/notebook/services/kernels/kernelmanager.py", line 160, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/jupyter_client/manager.py", line 259, in start_kernel
    **kw)
  File "/usr/local/lib/python2.7/site-packages/jupyter_client/manager.py", line 204, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/usr/local/lib/python2.7/site-packages/jupyter_client/launcher.py", line 128, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/usr/local/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Any ideas of how to fix this?
​

**Comment by jchavezlavalle** [comment]
@kkmann do you have ipykernel installed ? https://ipython.readthedocs.io/en/stable/install/kernel_install.html

**Comment by kkmann** [comment]
@devprincess thx for coming back to this! I played around for a bit (as I said ipykernel already worked like a charm). Turns out that the solution is rather boring ;) 
Since we build the image in sudo mode, IRkernel::installapec() installs the R kernel in the root directory, simply changing this to `R -e "install.packages('IRkernel'); IRkernel::installspec(prefix = '/usr/local')"` works fine for me, maybe you want to mention that in your tutorial since it might not be obvious to other R users as well?

**Comment by jchavezlavalle** [comment]
Sounds good, thanks for the update, would you mind closing the issue in any case? thanks! :+1: @kkmann

**Comment by kkmann** [comment]
sure my bad x)

**Comment by kkmann** [comment]
@devprincess sorry for opening this up again, but the current approach is not portable since the kernels are installed in the respective locations in the *host* filesystem.
Any idea of how to install the kernels in the container filesystem?
